/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import modelo.Jugador;
import modelo.Computador;
import controlador.RegistroJugadores;
import controlador.RegistroComputador;
/**
 *
 * @author User
 */
public class VentanaDerrota extends javax.swing.JFrame {

    /**
     * Creates new form VentanaDerrota
     */
    public VentanaDerrota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textoIDU = new javax.swing.JTextField();
        textoNombreU = new javax.swing.JTextField();
        textoAliasU = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonGrabar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        botonSaltar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(textoIDU, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 100, -1));
        jPanel1.add(textoNombreU, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 100, -1));
        jPanel1.add(textoAliasU, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 100, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Su ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 60, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 80, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setText("Alias");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 50, -1));

        botonGrabar.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        botonGrabar.setText("GRABAR");
        botonGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGrabarActionPerformed(evt);
            }
        });
        jPanel1.add(botonGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setText("DERROTA!");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 130, 40));

        botonSaltar.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        botonSaltar.setText("SALTAR");
        botonSaltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSaltarActionPerformed(evt);
            }
        });
        jPanel1.add(botonSaltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/spr10.1.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mensaje(String msg){
        javax.swing.JOptionPane.showMessageDialog(this, msg);
    }
    private void botonGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGrabarActionPerformed
        // TODO add your handling code here:
        String id=textoIDU.getText().trim();
        if (new RegistroJugadores().validarId(id) == false) {
            Jugador jug = new Jugador();
            Computador com = new Computador();
            jug.setId(id);
            jug.setNombre(textoNombreU.getText());
            jug.setAlias(textoAliasU.getText());
            jug.setCantidadVictorias(0);
            jug.setCantidadDerrotas(1);
            jug.setCantidadJuegos(1);
            com.setEstado("D");
            if (new RegistroJugadores().agregarJugador(jug)) {
                this.mensaje("GRABO JUGADOR!!!");
            } else {
                this.mensaje("NO GRABO JUGADOR!!!");
            }
            if (new RegistroComputador().agregarResultado(com)) {
                this.mensaje("GRABO RESULTADO!!!");
            } else {
                this.mensaje("NO GRABO RESULTADO!!!");
            }
        } else {
            Computador com = new Computador();
            com.setEstado("V");
            Jugador jug=new RegistroJugadores().buscarPorId(id);
            new RegistroJugadores().modificarJugadorD(jug);
            if (new RegistroComputador().agregarResultado(com)) {
                this.mensaje("GRABO RESULTADO!!!");
            } else {
                this.mensaje("NO GRABO RESULTADO!!!");
            }
        }
        this.setVisible(false);
        new VentanaPrincipal().setVisible(true);
    }//GEN-LAST:event_botonGrabarActionPerformed

    private void botonSaltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSaltarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new VentanaPrincipal().setVisible(true);
    }//GEN-LAST:event_botonSaltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDerrota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDerrota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDerrota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDerrota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDerrota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGrabar;
    private javax.swing.JButton botonSaltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textoAliasU;
    private javax.swing.JTextField textoIDU;
    private javax.swing.JTextField textoNombreU;
    // End of variables declaration//GEN-END:variables
}
