/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import controlador.Tablero;
import modelo.Barco;
import controlador.RegistroComputador;
/**
 *
 * @author User
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonPlay1P = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuRegistroJ = new javax.swing.JMenu();
        menuBuscarJugador = new javax.swing.JMenuItem();
        menuBorrarJugador = new javax.swing.JMenuItem();
        menuRegistroIA = new javax.swing.JMenu();
        menuMostrarPartidas = new javax.swing.JMenuItem();
        menuBorrarPartidas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonPlay1P.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        botonPlay1P.setText("Jugador Vs IA");
        botonPlay1P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPlay1PActionPerformed(evt);
            }
        });
        jPanel1.add(botonPlay1P, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, 160, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/spr11.1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 580));

        menuRegistroJ.setText("RegistroJugador");

        menuBuscarJugador.setText("Buscar por ID");
        menuBuscarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscarJugadorActionPerformed(evt);
            }
        });
        menuRegistroJ.add(menuBuscarJugador);

        menuBorrarJugador.setText("Borrar por ID");
        menuBorrarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBorrarJugadorActionPerformed(evt);
            }
        });
        menuRegistroJ.add(menuBorrarJugador);

        jMenuBar1.add(menuRegistroJ);

        menuRegistroIA.setText("RegistroIA");

        menuMostrarPartidas.setText("Mostrar partidas");
        menuMostrarPartidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMostrarPartidasActionPerformed(evt);
            }
        });
        menuRegistroIA.add(menuMostrarPartidas);

        menuBorrarPartidas.setText("Borrar registro");
        menuBorrarPartidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBorrarPartidasActionPerformed(evt);
            }
        });
        menuRegistroIA.add(menuBorrarPartidas);

        jMenuBar1.add(menuRegistroIA);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mensaje(String msg){
        javax.swing.JOptionPane.showMessageDialog(this, msg);
    }
    private void botonPlay1PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPlay1PActionPerformed
        // TODO add your handling code here:
        new VentanaPreparacionJ1P().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonPlay1PActionPerformed

    private void menuBuscarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscarJugadorActionPerformed
        // TODO add your handling code here:
        new VentanaMostrarJugadores().setVisible(true);
    }//GEN-LAST:event_menuBuscarJugadorActionPerformed

    private void menuBorrarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBorrarJugadorActionPerformed
        // TODO add your handling code here:
        new VentanaBorrarJugadores().setVisible(true);
    }//GEN-LAST:event_menuBorrarJugadorActionPerformed

    private void menuMostrarPartidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMostrarPartidasActionPerformed
        // TODO add your handling code here:
        new VentanaMostrarPartidas().setVisible(true);
    }//GEN-LAST:event_menuMostrarPartidasActionPerformed

    private void menuBorrarPartidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBorrarPartidasActionPerformed
        // TODO add your handling code here:
        new RegistroComputador().eliminar();
        this.mensaje("Elimino todo!!!");
    }//GEN-LAST:event_menuBorrarPartidasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPlay1P;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuBorrarJugador;
    private javax.swing.JMenuItem menuBorrarPartidas;
    private javax.swing.JMenuItem menuBuscarJugador;
    private javax.swing.JMenuItem menuMostrarPartidas;
    private javax.swing.JMenu menuRegistroIA;
    private javax.swing.JMenu menuRegistroJ;
    // End of variables declaration//GEN-END:variables
}
