/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import controlador.Tablero;
import controlador.MemoriaIA;
import modelo.Barco;
import java.util.Random;
//import java.util.ArrayList;
/**
 *
 * @author User
 */
public class VentanaPreparacionJ1P extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPreparacionJ1P
     */
    Barco barco0=new Barco();
    Barco barco1=new Barco("Barco", 'B');
    Tablero tableroJ=new Tablero();
    Tablero tableroIA=new Tablero();
    MemoriaIA memoriaIA=new MemoriaIA();
    //ArrayList<Integer> memoriaIA = new ArrayList<>();
    int contador=0;
    public VentanaPreparacionJ1P() {
        initComponents();
        for (int i = 0; i < 10; i++) {
            tableroJ.agregarBarco(barco0);
        } 
        for (int i = 0; i < 10; i++) {
            tableroIA.agregarBarco(barco0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textoC0 = new javax.swing.JTextField();
        textoC1 = new javax.swing.JTextField();
        textoC2 = new javax.swing.JTextField();
        textoC3 = new javax.swing.JTextField();
        textoC4 = new javax.swing.JTextField();
        textoC5 = new javax.swing.JTextField();
        textoC6 = new javax.swing.JTextField();
        textoC7 = new javax.swing.JTextField();
        textoC8 = new javax.swing.JTextField();
        textoC9 = new javax.swing.JTextField();
        textoBarcosColocados = new javax.swing.JTextField();
        textoBarcoColocado = new javax.swing.JTextField();
        botonColocar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        botonBonbardear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoC0.setText("A");

        textoC1.setText("A");
        textoC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoC1ActionPerformed(evt);
            }
        });

        textoC2.setText("A");

        textoC3.setText("A");

        textoC4.setText("A");

        textoC5.setText("A");

        textoC6.setText("A");

        textoC7.setText("A");

        textoC8.setText("A");

        textoC9.setText("A");

        textoBarcosColocados.setText("0");

        botonColocar.setText("COLOCAR");
        botonColocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonColocarActionPerformed(evt);
            }
        });

        jLabel1.setText("Campo1");

        jLabel2.setText("Campo2");

        jLabel3.setText("Campo3");

        jLabel4.setText("Campo4");

        jLabel5.setText("Campo5");

        jLabel6.setText("Campo6");

        jLabel7.setText("Campo7");

        jLabel8.setText("Campo8");

        jLabel9.setText("Campo9");

        jLabel10.setText("Campo10");

        jLabel11.setText("N° del campo");

        jLabel12.setText("Barcos colocados");

        botonBonbardear.setText("BOMBARDEAR");
        botonBonbardear.setEnabled(false);
        botonBonbardear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBonbardearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel8)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textoC0, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(textoC1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(textoC2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(textoC3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(textoC4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textoC5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(textoC6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(textoC7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(textoC8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(textoC9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(6, 6, 6)
                        .addComponent(textoBarcosColocados, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonBonbardear)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textoBarcoColocado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(botonColocar)))))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoC0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoC4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoC5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoC6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoC7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoC8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoC9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoBarcosColocados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoBarcoColocado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonColocar)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBonbardear)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoC1ActionPerformed

    private void botonColocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonColocarActionPerformed
        // TODO add your handling code here:
        int posBarco = Integer.parseInt(this.textoBarcoColocado.getText().trim()) - 1;
        if (posBarco == 0) {
            this.textoC0.setText("B");
            contador = contador + 1;
            this.textoBarcosColocados.setText(String.valueOf(contador));
            if (contador < 3) {
                tableroJ.modificarBarco(Integer.parseInt(this.textoBarcoColocado.getText().trim()) - 1, barco1);
                this.textoBarcoColocado.setText("");
            } else {
                this.textoBarcoColocado.setText("");
                this.textoBarcosColocados.setText("");
                this.botonColocar.setVisible(false);
                this.botonBonbardear.setEnabled(true);
                this.jLabel12.setText("Posición bombardeada");
                for (int i = 0; i < 3; i++) {
                    int intAleatorio = (int) (Math.random() * 9);
                    while (tableroIA.conseguirBarco(intAleatorio) == 'B') {
                        intAleatorio = (int) (Math.random() * 9);
                    }
                    tableroIA.modificarBarco(intAleatorio, barco1);
                    System.out.println(intAleatorio);
                }
            }
        } else if (posBarco == 1) {
            this.textoC1.setText("B");
            contador = contador + 1;
            this.textoBarcosColocados.setText(String.valueOf(contador));
            if (contador < 3) {
                tableroJ.modificarBarco(Integer.parseInt(this.textoBarcoColocado.getText().trim()) - 1, barco1);
                this.textoBarcoColocado.setText("");
            } else {
                this.textoBarcoColocado.setText("");
                this.textoBarcosColocados.setText("");
                this.botonColocar.setVisible(false);
                this.botonBonbardear.setEnabled(true);
                this.jLabel12.setText("Posición bombardeada");
                for (int i = 0; i < 3; i++) {
                    int intAleatorio = (int) (Math.random() * 9);
                    while (tableroIA.conseguirBarco(intAleatorio) == 'B') {
                        intAleatorio = (int) (Math.random() * 9);
                    }
                    tableroIA.modificarBarco(intAleatorio, barco1);
                    System.out.println(intAleatorio);
                }
            }
        } else if (posBarco == 2) {
            this.textoC2.setText("B");
            contador = contador + 1;
            this.textoBarcosColocados.setText(String.valueOf(contador));
            if (contador < 3) {
                tableroJ.modificarBarco(Integer.parseInt(this.textoBarcoColocado.getText().trim()) - 1, barco1);
                this.textoBarcoColocado.setText("");
            } else {
                this.textoBarcoColocado.setText("");
                this.textoBarcosColocados.setText("");
                this.botonColocar.setVisible(false);
                this.botonBonbardear.setEnabled(true);
                this.jLabel12.setText("Posición bombardeada");
                for (int i = 0; i < 3; i++) {
                    int intAleatorio = (int) (Math.random() * 9);
                    while (tableroIA.conseguirBarco(intAleatorio) == 'B') {
                        intAleatorio = (int) (Math.random() * 9);
                    }
                    tableroIA.modificarBarco(intAleatorio, barco1);
                    System.out.println(intAleatorio);
                }
            }
        } else if (posBarco == 3) {
            this.textoC3.setText("B");
            contador = contador + 1;
            this.textoBarcosColocados.setText(String.valueOf(contador));
            if (contador < 3) {
                tableroJ.modificarBarco(Integer.parseInt(this.textoBarcoColocado.getText().trim()) - 1, barco1);
                this.textoBarcoColocado.setText("");
            } else {
                this.textoBarcoColocado.setText("");
                this.textoBarcosColocados.setText("");
                this.botonColocar.setVisible(false);
                this.botonBonbardear.setEnabled(true);
                this.jLabel12.setText("Posición bombardeada");
                for (int i = 0; i < 3; i++) {
                    int intAleatorio = (int) (Math.random() * 9);
                    while (tableroIA.conseguirBarco(intAleatorio) == 'B') {
                        intAleatorio = (int) (Math.random() * 9);
                    }
                    tableroIA.modificarBarco(intAleatorio, barco1);
                    System.out.println(intAleatorio);
                }
            }
        } else if (posBarco == 4) {
            this.textoC4.setText("B");
            contador = contador + 1;
            this.textoBarcosColocados.setText(String.valueOf(contador));
            if (contador < 3) {
                tableroJ.modificarBarco(Integer.parseInt(this.textoBarcoColocado.getText().trim()) - 1, barco1);
                this.textoBarcoColocado.setText("");
            } else {
                this.textoBarcoColocado.setText("");
                this.textoBarcosColocados.setText("");
                this.botonColocar.setVisible(false);
                this.botonBonbardear.setEnabled(true);
                this.jLabel12.setText("Posición bombardeada");
                for (int i = 0; i < 3; i++) {
                    int intAleatorio = (int) (Math.random() * 9);
                    while (tableroIA.conseguirBarco(intAleatorio) == 'B') {
                        intAleatorio = (int) (Math.random() * 9);
                    }
                    tableroIA.modificarBarco(intAleatorio, barco1);
                    System.out.println(intAleatorio);
                }
            }
        } else if (posBarco == 5) {
            this.textoC5.setText("B");
            contador = contador + 1;
            this.textoBarcosColocados.setText(String.valueOf(contador));
            if (contador < 3) {
                tableroJ.modificarBarco(Integer.parseInt(this.textoBarcoColocado.getText().trim()) - 1, barco1);
                this.textoBarcoColocado.setText("");
            } else {
                this.textoBarcoColocado.setText("");
                this.textoBarcosColocados.setText("");
                this.botonColocar.setVisible(false);
                this.botonBonbardear.setEnabled(true);
                this.jLabel12.setText("Posición bombardeada");
                for (int i = 0; i < 3; i++) {
                    int intAleatorio = (int) (Math.random() * 9);
                    while (tableroIA.conseguirBarco(intAleatorio) == 'B') {
                        intAleatorio = (int) (Math.random() * 9);
                    }
                    tableroIA.modificarBarco(intAleatorio, barco1);
                    System.out.println(intAleatorio);
                }
            }
        } else if (posBarco == 6) {
            this.textoC6.setText("B");
            contador = contador + 1;
            this.textoBarcosColocados.setText(String.valueOf(contador));
            if (contador < 3) {
                tableroJ.modificarBarco(Integer.parseInt(this.textoBarcoColocado.getText().trim()) - 1, barco1);
                this.textoBarcoColocado.setText("");
            } else {
                this.textoBarcoColocado.setText("");
                this.textoBarcosColocados.setText("");
                this.botonColocar.setVisible(false);
                this.botonBonbardear.setEnabled(true);
                this.jLabel12.setText("Posición bombardeada");
                for (int i = 0; i < 3; i++) {
                    int intAleatorio = (int) (Math.random() * 9);
                    while (tableroIA.conseguirBarco(intAleatorio) == 'B') {
                        intAleatorio = (int) (Math.random() * 9);
                    }
                    tableroIA.modificarBarco(intAleatorio, barco1);
                    System.out.println(intAleatorio);
                }
            }
        } else if (posBarco == 7) {
            this.textoC7.setText("B");
            contador = contador + 1;
            this.textoBarcosColocados.setText(String.valueOf(contador));
            if (contador < 3) {
                tableroJ.modificarBarco(Integer.parseInt(this.textoBarcoColocado.getText().trim()) - 1, barco1);
                this.textoBarcoColocado.setText("");
            } else {
                this.textoBarcoColocado.setText("");
                this.textoBarcosColocados.setText("");
                this.botonColocar.setVisible(false);
                this.botonBonbardear.setEnabled(true);
                this.jLabel12.setText("Posición bombardeada");
                for (int i = 0; i < 3; i++) {
                    int intAleatorio = (int) (Math.random() * 9);
                    while (tableroIA.conseguirBarco(intAleatorio) == 'B') {
                        intAleatorio = (int) (Math.random() * 9);
                    }
                    tableroIA.modificarBarco(intAleatorio, barco1);
                    System.out.println(intAleatorio);
                }
            }
        } else if (posBarco == 8) {
            this.textoC8.setText("B");
            contador = contador + 1;
            this.textoBarcosColocados.setText(String.valueOf(contador));
            if (contador < 3) {
                tableroJ.modificarBarco(Integer.parseInt(this.textoBarcoColocado.getText().trim()) - 1, barco1);
                this.textoBarcoColocado.setText("");
            } else {
                this.textoBarcoColocado.setText("");
                this.textoBarcosColocados.setText("");
                this.botonColocar.setVisible(false);
                this.botonBonbardear.setEnabled(true);
                this.jLabel12.setText("Posición bombardeada");
                for (int i = 0; i < 3; i++) {
                    int intAleatorio = (int) (Math.random() * 9);
                    while (tableroIA.conseguirBarco(intAleatorio) == 'B') {
                        intAleatorio = (int) (Math.random() * 9);
                    }
                    tableroIA.modificarBarco(intAleatorio, barco1);
                    System.out.println(intAleatorio);
                }
            }
        } else if (posBarco == 9) {
            this.textoC9.setText("B");
            contador = contador + 1;
            this.textoBarcosColocados.setText(String.valueOf(contador));
            if (contador < 3) {
                tableroJ.modificarBarco(Integer.parseInt(this.textoBarcoColocado.getText().trim()) - 1, barco1);
                this.textoBarcoColocado.setText("");
            } else {
                this.textoBarcoColocado.setText("");
                this.textoBarcosColocados.setText("");
                this.botonColocar.setVisible(false);
                this.botonBonbardear.setEnabled(true);
                this.jLabel12.setText("Posición bombardeada");
                for (int i = 0; i < 3; i++) {
                    int intAleatorio = (int) (Math.random() * 9);
                    while (tableroIA.conseguirBarco(intAleatorio) == 'B') {
                        intAleatorio = (int) (Math.random() * 9);
                    }
                    tableroIA.modificarBarco(intAleatorio, barco1);
                    System.out.println(intAleatorio);
                }
            }
        } else {
            System.out.println("Error numero fuera de rango");
        }
    }//GEN-LAST:event_botonColocarActionPerformed

    private void botonBonbardearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBonbardearActionPerformed
        // TODO add your handling code here:
        tableroIA.modificarBarco(Integer.parseInt(this.textoBarcoColocado.getText().trim()) - 1, barco0);
        this.textoBarcoColocado.setText("");
        int intAleatorio = (int) (Math.random() * 9);
        //2da Solucion usando la clase memoria :(
        while (memoriaIA.validarNumero(intAleatorio)==true) {
            intAleatorio = (int) (Math.random() * 9);
        }
        memoriaIA.agregarNumero(intAleatorio);
        //Solucion "" al menos fuca pero aun asi repite numeros
//        while (tableroJ.indexarObjeto(tableroJ.consegirObjeto(intAleatorio))==intAleatorio) {
//            intAleatorio = (int) (Math.random() * 9);
//        }
        //1ra Solucion usando la Clase memoria IA :(
//        memoriaIA.agregarNumero(intAleatorio);
//        contador=(contador)+1;
//        while (memoriaIA.conseguirNumero(contador-1)==intAleatorio) {
//            intAleatorio = (int) (Math.random() * 9);
//        }
        System.out.println(intAleatorio);
        if (intAleatorio == 0) {
            this.textoC0.setText("A");
            tableroJ.modificarBarco(intAleatorio, barco0);
            this.textoBarcosColocados.setText("1");
        } else if (intAleatorio == 1) {
            this.textoC1.setText("A");
            tableroJ.modificarBarco(intAleatorio, barco0);
            this.textoBarcosColocados.setText("2");
        } else if (intAleatorio == 2) {
            this.textoC2.setText("A");
            tableroJ.modificarBarco(intAleatorio, barco0);
            this.textoBarcosColocados.setText("3");
        } else if (intAleatorio == 3) {
            this.textoC3.setText("A");
            tableroJ.modificarBarco(intAleatorio, barco0);
            this.textoBarcosColocados.setText("4");
        } else if (intAleatorio == 4) {
            this.textoC4.setText("A");
            tableroJ.modificarBarco(intAleatorio, barco0);
            this.textoBarcosColocados.setText("5");
        } else if (intAleatorio == 5) {
            this.textoC5.setText("A");
            tableroJ.modificarBarco(intAleatorio, barco0);
            this.textoBarcosColocados.setText("6");
        } else if (intAleatorio == 6) {
            this.textoC6.setText("A");
            tableroJ.modificarBarco(intAleatorio, barco0);
            this.textoBarcosColocados.setText("7");
        } else if (intAleatorio == 7) {
            this.textoC7.setText("A");
            tableroJ.modificarBarco(intAleatorio, barco0);
            this.textoBarcosColocados.setText("8");
        } else if (intAleatorio == 8) {
            this.textoC8.setText("A");
            tableroJ.modificarBarco(intAleatorio, barco0);
            this.textoBarcosColocados.setText("9");
        } else if (intAleatorio == 9) {
            this.textoC9.setText("A");
            tableroJ.modificarBarco(intAleatorio, barco0);
            this.textoBarcosColocados.setText("10");
        }
        if (tableroIA.validarVictoria() == true) {
            System.out.println("Victoria");
        } else if (tableroJ.validarVictoria() == true) {
            System.out.println("Derrota");
        } else if (tableroJ.validarVictoria() == true && tableroJ.validarVictoria() == true) {
            System.out.println("Empate"); 
        }
    }//GEN-LAST:event_botonBonbardearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPreparacionJ1P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPreparacionJ1P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPreparacionJ1P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPreparacionJ1P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPreparacionJ1P().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBonbardear;
    private javax.swing.JButton botonColocar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textoBarcoColocado;
    private javax.swing.JTextField textoBarcosColocados;
    private javax.swing.JTextField textoC0;
    private javax.swing.JTextField textoC1;
    private javax.swing.JTextField textoC2;
    private javax.swing.JTextField textoC3;
    private javax.swing.JTextField textoC4;
    private javax.swing.JTextField textoC5;
    private javax.swing.JTextField textoC6;
    private javax.swing.JTextField textoC7;
    private javax.swing.JTextField textoC8;
    private javax.swing.JTextField textoC9;
    // End of variables declaration//GEN-END:variables
}
